// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "7435833d-8623-4bc8-996a-05b65df28479");
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1791421264);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1791421742);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1791421261);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 181);
user_pref("browser.ml.chat.nimbus", "copilot-chatbot-sunset:control");
user_pref("browser.ml.onnxNativeAvailabilityReported", true);
user_pref("browser.newtabpage.activity-stream.impressionId", "{1bf252ec-2dab-4b72-ac24-22a4d93732d8}");
user_pref("browser.newtabpage.activity-stream.widgets.sportsWidget.enabled", false);
user_pref("browser.newtabpage.activity-stream.widgets.sportsWidget.pollLiveMs", 60000);
user_pref("browser.newtabpage.activity-stream.widgets.system.sportsWidget.enabled", false);
user_pref("browser.newtabpage.trainhopAddon.version", "156.2.20260824.60102");
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1791421742063");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1791443342063");
user_pref("browser.search.serpEventTelemetryCategorization.regionEnabled", false);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20260921121718");
user_pref("browser.startup.couldRestoreSession.count", 2);
user_pref("browser.startup.homepage_override.buildID", "20260921121718");
user_pref("browser.startup.homepage_override.mstone", "156.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1791421742);
user_pref("browser.termsofuse.prefMigrationCheck", true);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"vertical-spacer\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"reset-pbm-toolbar-button\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"customizableui-special-spring3\",\"alltabs-button\",\"smartwindow-group-tabs-button\",\"ai-window-toggle\"],\"vertical-tabs\":[],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"reset-pbm-toolbar-button\",\"smartwindow-group-tabs-button\",\"ai-window-toggle\",\"developer-button\",\"screenshot-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"TabsToolbar\",\"vertical-tabs\",\"PersonalToolbar\",\"toolbar-menubar\"],\"currentVersion\":26,\"newElementCount\":3}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.placeholderName.private", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 7);
user_pref("captchadetection.lastSubmission", 1791421);
user_pref("datareporting.dau.cachedUsageProfileGroupID", "135484fc-0a9d-4ffa-93e3-6fdd5a2cf9cf");
user_pref("datareporting.dau.cachedUsageProfileID", "c5088dc9-eb8b-44b4-92d3-5aa38b522fb2");
user_pref("distribution.iniFile.exists.appversion", "156.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("distribution.mozilla-deb.bookmarksProcessed", true);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "e198b918ea2d408fa1b6f6bf1d59e930");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.colorway-builtin-themes-cleanup", 1);
user_pref("extensions.databaseSchema", 37);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20260921121718");
user_pref("extensions.lastAppVersion", "156.0.1");
user_pref("extensions.lastPlatformVersion", "156.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.signatureCheckpoint", 1);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"124f0b4f-ec70-479f-bdc0-5b081b35eaac\",\"ipp-activator@mozilla.com\":\"30f26f6f-9f58-48a6-9d82-2bdbf2f66413\",\"pictureinpicture@mozilla.org\":\"353c2bb4-9ae5-481d-94c4-0ed37ceef12b\",\"addons-search-detection@mozilla.com\":\"6c850f4e-074e-49c6-9928-06a1f5198f7c\",\"webcompat@mozilla.org\":\"9a310967-e580-48bf-b3e8-4eafebbc122d\",\"newtab@mozilla.org\":\"4e4c5136-1270-4b0f-9acd-d40c272c734c\",\"default-theme@mozilla.org\":\"8d430810-01c6-4945-ae54-81ba6713712f\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.CHIPS.lastMigrateDatabase", 2);
user_pref("network.cookie.validation.lastEpoch", 1);
user_pref("nimbus.firstUpdateComplete", true);
user_pref("nimbus.migrations.after-remote-settings-update", 0);
user_pref("nimbus.migrations.after-store-initialized", 5);
user_pref("nimbus.migrations.init-started", 1);
user_pref("nimbus.profileId", "a077c95d-afbe-45bb-975e-b6e4419c5d6c");
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("privacy.clearOnShutdown_v2.formdata", true);
user_pref("privacy.sanitize.clearOnShutdown.hasMigratedToNewPrefs3", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref("services.settings.base_attachments_url", "https://firefox.settings.services.mozilla.com/v2|https://firefox-settings-attachments.cdn.mozilla.net/");
user_pref("services.sync.engine.addresses.available", true);
user_pref("sidebar.backupState", "{\"command\":\"\",\"panelOpen\":false,\"bookmarksExpandedFolders\":[],\"launcherExpanded\":false,\"launcherVisible\":false}");
user_pref("sidebar.visibility", "hide-on-close");
user_pref("signon.storage.rust.restoreDone", true);
user_pref("telemetry.fog.init_on_shutdown", false);
user_pref("toolkit.profiles.newProfileSubmitted", true);
user_pref("toolkit.profiles.storeID", "82679442");
user_pref("toolkit.startup.last_success", 1791421739);
user_pref("toolkit.telemetry.cachedClientID", "9cc6a436-4742-40ab-8194-9fcdb030bf05");
user_pref("toolkit.telemetry.cachedProfileGroupID", "ebf327f7-2950-41ae-87ce-e044a11b12eb");
user_pref("toolkit.telemetry.previousBuildID", "20260921121718");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
