var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.createTemplateTagFirstArg=function(a){return $jscomp.createTemplateTagFirstArgWithRaw(a,a)};$jscomp.createTemplateTagFirstArgWithRaw=function(a,b){a.raw=b;Object.freeze&&(Object.freeze(a),Object.freeze(b));return a};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};
$jscomp.makeIterator=function(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return $jscomp.arrayIterator(a);throw Error(String(a)+" is not an iterable or ArrayLike");};$jscomp.ASSUME_ES2020=!1;$jscomp.ASSUME_ES6=$jscomp.ASSUME_ES2020;$jscomp.ASSUME_ES5=$jscomp.ASSUME_ES6;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;$jscomp.INSTRUMENT_ASYNC_CONTEXT=!0;$jscomp.defineProperty=$jscomp.ASSUME_ES5||typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.ASSUME_ES2020?globalThis:$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE=typeof Symbol==="function"&&typeof Symbol("x")==="symbol";$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;
$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var JSCompiler_inline_result$jscomp$0,classes$jscomp$inline_2="Int8 Uint8 Uint8Clamped Int16 Uint16 Int32 Uint32 Float32 Float64".split(" ");$jscomp.global.BigInt64Array&&(classes$jscomp$inline_2.push("BigInt64"),classes$jscomp$inline_2.push("BigUint64"));JSCompiler_inline_result$jscomp$0=classes$jscomp$inline_2;$jscomp.TYPED_ARRAY_CLASSES=JSCompiler_inline_result$jscomp$0;
$jscomp.polyfillTypedArrayMethod=function(a,b,c,d){if(b)for(var e=0;e<$jscomp.TYPED_ARRAY_CLASSES.length;e++){var f=$jscomp.TYPED_ARRAY_CLASSES[e]+"Array.prototype."+a;$jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(f,b,c,d):$jscomp.polyfillUnisolated(f,b,c,d)}};$jscomp.polyfill=function(a,b,c,d){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,c,d):$jscomp.polyfillUnisolated(a,b,c,d))};
$jscomp.polyfillUnisolated=function(a,b){var c=$jscomp.global;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))return;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,c){var d=a.split("."),e=d.length===1;a=d[0];a=!e&&a in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var f=0;f<d.length-1;f++){var g=d[f];if(!(g in a))return;a=a[g]}d=d[d.length-1];c=$jscomp.IS_SYMBOL_NATIVE&&c==="es6"?a[d]:null;b=b(c);b!=null&&(e?$jscomp.defineProperty($jscomp.polyfills,d,{configurable:!0,writable:!0,value:b}):b!==c&&($jscomp.propertyToPolyfillSymbol[d]===void 0&&(e=Math.random()*1E9>>>0,$jscomp.propertyToPolyfillSymbol[d]=$jscomp.IS_SYMBOL_NATIVE?
$jscomp.global.Symbol(d):$jscomp.POLYFILL_PREFIX+e+"$"+d),e=$jscomp.propertyToPolyfillSymbol[d],$jscomp.defineProperty(a,e,{configurable:!0,writable:!0,value:b})))};$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},b={};try{return b.__proto__=a,b.a}catch(c){}return!1};
$jscomp.setPrototypeOf=$jscomp.ASSUME_ES6||$jscomp.TRUST_ES6_POLYFILLS&&typeof Object.setPrototypeOf=="function"?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null;$jscomp.polyfill("Object.setPrototypeOf",function(a){return a||$jscomp.setPrototypeOf},"es6","es5");$jscomp.owns=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
$jscomp.toObject=function(a){if(a==null)throw new TypeError("No nullish arg");return Object(a)};$jscomp.assign=$jscomp.ASSUME_ES6||$jscomp.TRUST_ES6_POLYFILLS&&typeof Object.assign=="function"?Object.assign:function(a,b){a=$jscomp.toObject(a);for(var c=1;c<arguments.length;c++){var d=arguments[c];if(d)for(var e in d)$jscomp.owns(d,e)&&(a[e]=d[e])}return a};$jscomp.initSymbol=function(){};
$jscomp.polyfill("Symbol",function(a){if(a)return a;var b=function(f,g){this.$jscomp$symbol$id_=f;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:g})};b.prototype.toString=function(){return this.$jscomp$symbol$id_};a=Math.random()*1E9>>>0;var c="jscomp_symbol_"+a+"_",d=0,e=function(f){if(this instanceof e)throw new TypeError("Symbol is not a constructor");return new b(c+(f||"")+"_"+d++,f)};return e},"es6","es3");
$jscomp.polyfill("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});return a},"es6","es3");$jscomp.iteratorPrototype=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a};
$jscomp.objectCreate=$jscomp.ASSUME_ES5||typeof Object.create=="function"?Object.create:function(a){var b=function(){};b.prototype=a;return new b};$jscomp.inherits=function(a,b){a.prototype=$jscomp.objectCreate(b.prototype);a.prototype.constructor=a;if($jscomp.ASSUME_ES6||$jscomp.setPrototypeOf){var c=$jscomp.setPrototypeOf;c(a,b)}else for(c in b)if(c!="prototype")if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.superClass_=b.prototype};
$jscomp.getConstructImplementation=function(){function a(){function e(){}function f(){}new e;Reflect.construct(e,[],f);return new e instanceof e}function b(e,f,g){g===void 0&&(g=e);g=g.prototype||Object.prototype;g=$jscomp.objectCreate(g);var m=Function.prototype.apply;return(e=m.call(e,g,f))||g}if($jscomp.TRUST_ES6_POLYFILLS&&typeof Reflect!="undefined"&&Reflect.construct){if(a())return Reflect.construct;var c=Reflect.construct,d=function(e,f,g){e=c(e,f);g&&Reflect.setPrototypeOf(e,g.prototype);
return e};return d}return b};$jscomp.construct={valueOf:$jscomp.getConstructImplementation}.valueOf();$jscomp.polyfill("Reflect",function(a){return a?a:{}},"es6","es3");$jscomp.polyfill("Reflect.construct",function(){return $jscomp.construct},"es6","es3");
$jscomp.checkStringArgs=function(a,b,c){if(a==null)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""};
$jscomp.polyfill("String.prototype.startsWith",function(a){return a?a:a=function(b,c){var d=$jscomp.checkStringArgs(this,b,"startsWith");b+="";var e=d.length,f=b.length;c=Math.max(0,Math.min(c|0,d.length));for(var g=0;g<f&&c<e;)if(d[c++]!=b[g++])return!1;return g>=f}},"es6","es3");$jscomp.polyfill("Object.is",function(a){return a?a:a=function(b,c){return b===c?b!==0||1/b===1/c:b!==b&&c!==c}},"es6","es3");
$jscomp.polyfill("Array.prototype.includes",function(a){return a?a:a=function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(c<0&&(c=Math.max(c+e,0));c<e;c++){var f=d[c];if(f===b||Object.is(f,b))return!0}return!1}},"es7","es3");$jscomp.polyfill("String.prototype.includes",function(a){return a?a:a=function(b,c){var d=$jscomp.checkStringArgs(this,b,"includes");return d.indexOf(b,c||0)!==-1}},"es6","es3");
$jscomp.checkEs6ConformanceViaProxy=function(){try{var a={},b=Object.create(new $jscomp.global.Proxy(a,{get:function(c,d,e){return c==a&&d=="q"&&e==b}}));return b.q===!0}catch(c){return!1}};$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS=!1;$jscomp.ES6_CONFORMANCE=$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS&&$jscomp.checkEs6ConformanceViaProxy();
$jscomp.polyfill("WeakMap",function(a){function b(){if(!a||!Object.seal)return!1;try{var h=Object.seal({}),k=Object.seal({}),n=new a([[h,2],[k,3]]);if(n.get(h)!=2||n.get(k)!=3)return!1;n.delete(h);n.set(k,4);return!n.has(h)&&n.get(k)==4}catch(r){return!1}}function c(){}function d(h){var k=typeof h;return k==="object"&&h!==null||k==="function"}function e(h){if(!$jscomp.owns(h,g)){var k=new c;$jscomp.defineProperty(h,g,{value:k})}}function f(h){if(!$jscomp.ISOLATE_POLYFILLS){var k=Object[h];k&&(Object[h]=
function(n){if(n instanceof c)return n;Object.isExtensible(n)&&e(n);return k(n)})}}if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(a&&$jscomp.ES6_CONFORMANCE)return a}else if(b())return a;var g="$jscomp_hidden_"+Math.random();f("freeze");f("preventExtensions");f("seal");var m=0,l=function(h){this.id_=(m+=Math.random()+1).toString();if(h){h=$jscomp.makeIterator(h);for(var k;!(k=h.next()).done;)k=k.value,this.set(k[0],k[1])}};l.prototype.set=function(h,k){if(!d(h))throw Error("Invalid WeakMap key");
e(h);if(!$jscomp.owns(h,g))throw Error("WeakMap key fail: "+h);h[g][this.id_]=k;return this};l.prototype.get=function(h){return d(h)&&$jscomp.owns(h,g)?h[g][this.id_]:void 0};l.prototype.has=function(h){return d(h)&&$jscomp.owns(h,g)&&$jscomp.owns(h[g],this.id_)};l.prototype.delete=function(h){return d(h)&&$jscomp.owns(h,g)&&$jscomp.owns(h[g],this.id_)?delete h[g][this.id_]:!1};return l},"es6","es3");$jscomp.MapEntry=function(){};
$jscomp.polyfill("Map",function(a){function b(){if($jscomp.ASSUME_NO_NATIVE_MAP||!a||typeof a!="function"||!a.prototype.entries||typeof Object.seal!="function")return!1;try{var l=Object.seal({x:4}),h=new a($jscomp.makeIterator([[l,"s"]]));if(h.get(l)!="s"||h.size!=1||h.get({x:4})||h.set({x:4},"t")!=h||h.size!=2)return!1;var k=h.entries(),n=k.next();if(n.done||n.value[0]!=l||n.value[1]!="s")return!1;n=k.next();return n.done||n.value[0].x!=4||n.value[1]!="t"||!k.next().done?!1:!0}catch(r){return!1}}
if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(a&&$jscomp.ES6_CONFORMANCE)return a}else if(b())return a;var c=new WeakMap,d=function(l){this[0]={};this[1]=g();this.size=0;if(l){l=$jscomp.makeIterator(l);for(var h;!(h=l.next()).done;)h=h.value,this.set(h[0],h[1])}};d.prototype.set=function(l,h){l=l===0?0:l;var k=e(this,l);k.list||(k.list=this[0][k.id]=[]);k.entry?k.entry.value=h:(k.entry={next:this[1],previous:this[1].previous,head:this[1],key:l,value:h},k.list.push(k.entry),this[1].previous.next=
k.entry,this[1].previous=k.entry,this.size++);return this};d.prototype.delete=function(l){l=e(this,l);return l.entry&&l.list?(l.list.splice(l.index,1),l.list.length||delete this[0][l.id],l.entry.previous.next=l.entry.next,l.entry.next.previous=l.entry.previous,l.entry.head=null,this.size--,!0):!1};d.prototype.clear=function(){this[0]={};this[1]=this[1].previous=g();this.size=0};d.prototype.has=function(l){return!!e(this,l).entry};d.prototype.get=function(l){return(l=e(this,l).entry)&&l.value};d.prototype.entries=
function(){return f(this,function(l){return[l.key,l.value]})};d.prototype.keys=function(){return f(this,function(l){return l.key})};d.prototype.values=function(){return f(this,function(l){return l.value})};d.prototype.forEach=function(l,h){for(var k=this.entries(),n;!(n=k.next()).done;)n=n.value,l.call(h,n[1],n[0],this)};d.prototype[Symbol.iterator]=d.prototype.entries;var e=function(l,h){var k;var n=(k=h)&&typeof k;n=="object"||n=="function"?c.has(k)?k=c.get(k):(n=""+ ++m,c.set(k,n),k=n):k="p_"+
k;if((n=l[0][k])&&$jscomp.owns(l[0],k))for(l=0;l<n.length;l++){var r=n[l];if(h!==h&&r.key!==r.key||h===r.key)return{id:k,list:n,index:l,entry:r}}return{id:k,list:n,index:-1,entry:void 0}},f=function(l,h){var k=l[1];return $jscomp.iteratorPrototype(function(){if(k){for(;k.head!=l[1];)k=k.previous;for(;k.next!=k.head;)return k=k.next,{done:!1,value:h(k)};k=null}return{done:!0,value:void 0}})},g=function(){var l={};return l.previous=l.next=l.head=l},m=0;return d},"es6","es3");
$jscomp.polyfill("Set",function(a){function b(){if($jscomp.ASSUME_NO_NATIVE_SET||!a||typeof a!="function"||!a.prototype.entries||typeof Object.seal!="function")return!1;try{var d=Object.seal({x:4}),e=new a($jscomp.makeIterator([d]));if(!e.has(d)||e.size!=1||e.add(d)!=e||e.size!=1||e.add({x:4})!=e||e.size!=2)return!1;var f=e.entries(),g=f.next();if(g.done||g.value[0]!=d||g.value[1]!=d)return!1;g=f.next();return g.done||g.value[0]==d||g.value[0].x!=4||g.value[1]!=g.value[0]?!1:f.next().done}catch(m){return!1}}
if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(a&&$jscomp.ES6_CONFORMANCE)return a}else if(b())return a;var c=function(d){this.map_=new Map;if(d){d=$jscomp.makeIterator(d);for(var e;!(e=d.next()).done;)e=e.value,this.add(e)}this.size=this.map_.size};c.prototype.add=function(d){d=d===0?0:d;this.map_.set(d,d);this.size=this.map_.size;return this};c.prototype.delete=function(d){d=this.map_.delete(d);this.size=this.map_.size;return d};c.prototype.clear=function(){this.map_.clear();this.size=0};c.prototype.has=
function(d){return this.map_.has(d)};c.prototype.entries=function(){return this.map_.entries()};c.prototype.values=function(){return this.map_.values()};c.prototype.keys=c.prototype.values;c.prototype[Symbol.iterator]=c.prototype.values;c.prototype.forEach=function(d,e){var f=this;this.map_.forEach(function(g){return d.call(e,g,g,f)})};return c},"es6","es3");
$jscomp.findInternal=function(a,b,c){a instanceof String&&(a=String(a));for(var d=a.length,e=0;e<d;e++){var f=a[e];if(b.call(c,f,e,a))return{i:e,v:f}}return{i:-1,v:void 0}};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:a=function(b,c){return $jscomp.findInternal(this,b,c).v}},"es6","es3");
$jscomp.polyfill("Array.from",function(a){return a?a:a=function(b,c,d){c=c!=null?c:function(m){return m};var e=[],f=typeof Symbol!="undefined"&&Symbol.iterator&&b[Symbol.iterator];if(typeof f=="function"){b=f.call(b);for(var g=0;!(f=b.next()).done;)e.push(c.call(d,f.value,g++))}else for(f=b.length,g=0;g<f;g++)e.push(c.call(d,b[g],g));return e}},"es6","es3");$jscomp.polyfill("Array.prototype.findIndex",function(a){return a?a:a=function(b,c){return $jscomp.findInternal(this,b,c).i}},"es6","es3");
$jscomp.polyfill("WeakSet",function(a){function b(){if(!a||!Object.seal)return!1;try{var d=Object.seal({}),e=Object.seal({}),f=new a([d]);if(!f.has(d)||f.has(e))return!1;f.delete(d);f.add(e);return!f.has(d)&&f.has(e)}catch(g){return!1}}if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(a&&$jscomp.ES6_CONFORMANCE)return a}else if(b())return a;var c=function(d){this.map_=new WeakMap;if(d){d=$jscomp.makeIterator(d);for(var e;!(e=d.next()).done;)e=e.value,this.add(e)}};c.prototype.add=function(d){this.map_.set(d,
!0);return this};c.prototype.has=function(d){return this.map_.has(d)};c.prototype.delete=function(d){return this.map_.delete(d)};return c},"es6","es3");/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var goog=goog||{};goog.global=this||self;goog.exportPath_=function(a,b,c,d){a=a.split(".");d=d||goog.global;for(var e;a.length&&(e=a.shift());)if(a.length||b===void 0)d=d[e]&&d[e]!==Object.prototype[e]?d[e]:d[e]={};else if(!c&&goog.isObject(b)&&goog.isObject(d[e]))for(var f in b)b.hasOwnProperty(f)&&(d[e][f]=b[f]);else d[e]=b};goog.CLOSURE_DEFINES=typeof CLOSURE_DEFINES!=="undefined"?CLOSURE_DEFINES:goog.global.CLOSURE_DEFINES;
goog.CLOSURE_UNCOMPILED_DEFINES=typeof CLOSURE_UNCOMPILED_DEFINES!=="undefined"?CLOSURE_UNCOMPILED_DEFINES:goog.global.CLOSURE_UNCOMPILED_DEFINES;goog.define=function(a,b){return a=b};goog.FEATURESET_YEAR=2012;goog.DEBUG=!0;goog.LOCALE="en";goog.TRUSTED_SITE=!0;goog.DISALLOW_TEST_ONLY_CODE=!goog.DEBUG;goog.ENABLE_CHROME_APP_SAFE_SCRIPT_LOADING=!1;goog.readFlagInternalDoNotUseOrElse=function(a,b){var c=goog.getObjectByName(goog.FLAGS_OBJECT_);a=c&&c[a];return a!=null?a:b};goog.FLAGS_OBJECT_="CLOSURE_FLAGS";
goog.FLAGS_STAGING_DEFAULT=!0;goog.CLOSURE_TOGGLE_ORDINALS=typeof CLOSURE_TOGGLE_ORDINALS==="object"?CLOSURE_TOGGLE_ORDINALS:goog.global.CLOSURE_TOGGLE_ORDINALS;goog.readToggleInternalDoNotCallDirectly=function(a){var b=goog.CLOSURE_TOGGLE_ORDINALS;a=b&&b[a];return typeof a!=="number"?!!a:!!(goog.TOGGLES_[Math.floor(a/30)]&1<<a%30)};goog.TOGGLE_VAR_="_F_toggles";goog.TOGGLES_=goog.global[goog.TOGGLE_VAR_]||[];goog.GENDERED_MESSAGES_ENABLED=!0;
goog.GrammaticalGender_={OTHER:0,MASCULINE:1,FEMININE:2,NEUTER:3};goog.GRAMMATICAL_GENDER_MAP_={FEMININE:goog.GrammaticalGender_.FEMININE,MASCULINE:goog.GrammaticalGender_.MASCULINE,NEUTER:goog.GrammaticalGender_.NEUTER};goog.viewerGrammaticalGender_=goog.GRAMMATICAL_GENDER_MAP_[goog.GENDERED_MESSAGES_ENABLED&&goog.global._F_VIEWER_GRAMMATICAL_GENDER]||goog.GrammaticalGender_.OTHER;goog.msgKind={};goog.msgKind.MASCULINE=goog.viewerGrammaticalGender_===goog.GrammaticalGender_.MASCULINE;
goog.msgKind.FEMININE=goog.viewerGrammaticalGender_===goog.GrammaticalGender_.FEMININE;goog.msgKind.NEUTER=goog.viewerGrammaticalGender_===goog.GrammaticalGender_.NEUTER;goog.LEGACY_NAMESPACE_OBJECT_=goog.global;goog.provide=function(a){if(goog.isInModuleLoader_())throw Error("goog.provide cannot be used within a module.");goog.constructNamespace_(a)};goog.constructNamespace_=function(a,b,c){goog.exportPath_(a,b,c,goog.LEGACY_NAMESPACE_OBJECT_)};goog.NONCE_PATTERN_=/^[\w+/_-]+[=]{0,2}$/;
goog.getScriptNonce_=function(a){a=(a||goog.global).document;return(a=a.querySelector&&a.querySelector("script[nonce]"))&&(a=a.nonce||a.getAttribute("nonce"))&&goog.NONCE_PATTERN_.test(a)?a:""};goog.VALID_MODULE_RE_=/^[a-zA-Z_$][a-zA-Z0-9._$]*$/;goog.module=function(){};goog.module.get=function(){return null};goog.module.getInternal_=function(){return null};goog.requireDynamic=function(){return null};goog.importHandler_=null;goog.uncompiledChunkIdHandler_=null;
goog.setImportHandlerInternalDoNotCallOrElse=function(a){goog.importHandler_=a};goog.setUncompiledChunkIdHandlerInternalDoNotCallOrElse=function(a){goog.uncompiledChunkIdHandler_=a};goog.maybeRequireFrameworkInternalOnlyDoNotCallOrElse=function(){};goog.ModuleType={ES6:"es6",GOOG:"goog"};goog.moduleLoaderState_=null;goog.isInModuleLoader_=function(){return goog.isInGoogModuleLoader_()||goog.isInEs6ModuleLoader_()};
goog.isInGoogModuleLoader_=function(){return!!goog.moduleLoaderState_&&goog.moduleLoaderState_.type==goog.ModuleType.GOOG};goog.isInEs6ModuleLoader_=function(){var a=!!goog.moduleLoaderState_&&goog.moduleLoaderState_.type==goog.ModuleType.ES6;return a?!0:(a=goog.LEGACY_NAMESPACE_OBJECT_.$jscomp)?typeof a.getCurrentModulePath!="function"?!1:!!a.getCurrentModulePath():!1};goog.module.declareLegacyNamespace=function(){goog.moduleLoaderState_.declareLegacyNamespace=!0};
goog.module.preventModuleExportSealing=function(){goog.moduleLoaderState_.preventModuleExportSealing=!0};goog.declareModuleId=function(a){if(goog.moduleLoaderState_)goog.moduleLoaderState_.moduleName=a;else{var b=goog.LEGACY_NAMESPACE_OBJECT_.$jscomp;if(!b||typeof b.getCurrentModulePath!="function")throw Error('Module with namespace "'+a+'" has been loaded incorrectly.');b=b.require(b.getCurrentModulePath());goog.loadedModules_[a]={exports:b,type:goog.ModuleType.ES6,moduleId:a}}};
goog.setTestOnly=function(a){if(goog.DISALLOW_TEST_ONLY_CODE)throw a=a||"",Error("Importing test-only code into non-debug environment"+(a?": "+a:"."));};goog.forwardDeclare=function(){};goog.getObjectByName=function(a,b){a=a.split(".");b=b||goog.global;for(var c=0;c<a.length;c++)if(b=b[a[c]],b==null)return null;return b};goog.addDependency=function(){};goog.ENABLE_DEBUG_LOADER=!1;goog.logToConsole_=function(a){goog.global.console&&goog.global.console.error(a)};goog.require=function(){};
goog.requireType=function(){return{}};goog.basePath="";goog.abstractMethod=function(){throw Error("unimplemented abstract method");};goog.addSingletonGetter=function(a){a.instance_=void 0;a.getInstance=function(){if(a.instance_)return a.instance_;goog.DEBUG&&(goog.instantiatedSingletons_[goog.instantiatedSingletons_.length]=a);return a.instance_=new a}};goog.instantiatedSingletons_=[];goog.LOAD_MODULE_USING_EVAL=!0;goog.SEAL_MODULE_EXPORTS=goog.DEBUG;
goog.PREVENT_MODULE_EXPORTS_SEALING_SYMBOL_=typeof Symbol==="function"?Symbol("preventModuleExportSealing"):null;goog.loadedModules_={};goog.DEPENDENCIES_ENABLED=!1;goog.ASSUME_ES_MODULES_TRANSPILED=!1;goog.TRUSTED_TYPES_POLICY_NAME="goog";
goog.loadModule=function(a){var b=goog.moduleLoaderState_;try{goog.moduleLoaderState_={moduleName:"",declareLegacyNamespace:!1,preventModuleExportSealing:!1,type:goog.ModuleType.GOOG};var c={},d=c;if(typeof a==="function")d=a.call(void 0,d);else if(typeof a==="string")d=goog.loadModuleFromSource_.call(void 0,d,a);else throw Error("Invalid module definition");var e=goog.moduleLoaderState_.moduleName;if(typeof e==="string"&&e){if(goog.moduleLoaderState_.declareLegacyNamespace)a=c!==d,goog.constructNamespace_(e,
d,a);else if(goog.SEAL_MODULE_EXPORTS&&Object.seal&&typeof d=="object"&&d!=null)if(goog.moduleLoaderState_.preventModuleExportSealing){if(goog.PREVENT_MODULE_EXPORTS_SEALING_SYMBOL_&&Object.defineProperty)try{Object.defineProperty(d,goog.PREVENT_MODULE_EXPORTS_SEALING_SYMBOL_,{value:!0,writable:!1,enumerable:!1,configurable:!0})}catch(g){}}else goog.PREVENT_MODULE_EXPORTS_SEALING_SYMBOL_&&Object.prototype.hasOwnProperty.call(d,goog.PREVENT_MODULE_EXPORTS_SEALING_SYMBOL_)||Object.seal(d);var f={exports:d,
type:goog.ModuleType.GOOG,moduleId:goog.moduleLoaderState_.moduleName};goog.loadedModules_[e]=f}else throw Error('Invalid module name "'+e+'"');}finally{goog.moduleLoaderState_=b}};goog.loadModuleFromSource_=function(a){eval(goog.CLOSURE_EVAL_PREFILTER_.createScript(arguments[1]));return a};goog.normalizePath_=function(a){a=a.split("/");for(var b=0;b<a.length;)a[b]=="."?a.splice(b,1):b&&a[b]==".."&&a[b-1]&&a[b-1]!=".."?a.splice(--b,2):b++;return a.join("/")};
goog.loadFileSync_=function(a){if(goog.global.CLOSURE_LOAD_FILE_SYNC)return goog.global.CLOSURE_LOAD_FILE_SYNC(a);try{var b=new goog.global.XMLHttpRequest;b.open("get",a,!1);b.send();return b.status==0||b.status==200?b.responseText:null}catch(c){return null}};goog.typeOf=function(a){var b=typeof a;return b!="object"?b:a?Array.isArray(a)?"array":b:"null"};goog.isArrayLike=function(a){var b=goog.typeOf(a);return b=="array"||b=="object"&&typeof a.length=="number"};
goog.isDateLike=function(a){return goog.isObject(a)&&typeof a.getFullYear=="function"};goog.isObject=function(a){var b=typeof a;return b=="object"&&a!=null||b=="function"};goog.getUid=function(a){return Object.prototype.hasOwnProperty.call(a,goog.UID_PROPERTY_)&&a[goog.UID_PROPERTY_]||(a[goog.UID_PROPERTY_]=++goog.uidCounter_)};goog.hasUid=function(a){return!!a[goog.UID_PROPERTY_]};goog.removeUid=function(a){a!==null&&"removeAttribute"in a&&a.removeAttribute(goog.UID_PROPERTY_);try{delete a[goog.UID_PROPERTY_]}catch(b){}};
goog.UID_PROPERTY_="closure_uid_"+(Math.random()*1E9>>>0);goog.uidCounter_=0;goog.cloneObject=function(a){var b=goog.typeOf(a);if(b=="object"||b=="array"){if(typeof a.clone==="function")return a.clone();if(typeof Map!=="undefined"&&a instanceof Map)return new Map(a);if(typeof Set!=="undefined"&&a instanceof Set)return new Set(a);b=b=="array"?[]:{};for(var c in a)b[c]=goog.cloneObject(a[c]);return b}return a};goog.bindNative_=function(a,b,c){return a.call.apply(a.bind,arguments)};
goog.bindJs_=function(a,b,c){if(!a)throw Error();if(arguments.length>2){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}};
goog.bind=function(a,b,c){goog.bind=goog.TRUSTED_SITE&&goog.FEATURESET_YEAR>2012||Function.prototype.bind&&Function.prototype.bind.toString().indexOf("native code")!=-1?goog.bindNative_:goog.bindJs_;return goog.bind.apply(null,arguments)};goog.partial=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}};goog.now=function(){return Date.now()};goog.globalEval=function(a){(0,eval)(a)};
goog.getCssName=function(a,b){if(String(a).charAt(0)==".")throw Error('className passed in goog.getCssName must not start with ".". You passed: '+a);var c=function(e){return goog.cssNameMapping_[e]||e},d=function(e){e=e.split("-");for(var f=[],g=0;g<e.length;g++)f.push(c(e[g]));return f.join("-")};d=goog.cssNameMapping_?goog.cssNameMappingStyle_=="BY_WHOLE"?c:d:function(e){return e};a=b?a+"-"+d(b):d(a);return goog.global.CLOSURE_CSS_NAME_MAP_FN?goog.global.CLOSURE_CSS_NAME_MAP_FN(a):a};
goog.setCssNameMapping=function(a,b){goog.cssNameMapping_=a;goog.cssNameMappingStyle_=b};goog.GetMsgOptions=function(){};goog.USE_GET_MSG_OVERRIDE=!1;goog.getMsg=function(a,b,c){c&&c.html&&(a=a.replace(/</g,"&lt;"));c&&c.unescapeHtmlEntities&&(a=a.replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&apos;/g,"'").replace(/&quot;/g,'"').replace(/&amp;/g,"&"));b&&(a=a.replace(/\{\$([^}]+)}/g,function(d,e){return b!=null&&e in b?b[e]:d}));return a};goog.getMsgWithFallback=function(a){return a};
goog.exportSymbol=function(a,b,c){goog.exportPath_(a,b,!0,c)};goog.exportProperty=function(a,b,c){a[b]=c};goog.weakUsage=function(a){return a};goog.inherits=function(a,b){function c(){}c.prototype=b.prototype;a.superClass_=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.base=function(d,e,f){for(var g=Array(arguments.length-2),m=2;m<arguments.length;m++)g[m-2]=arguments[m];return b.prototype[e].apply(d,g)}};
goog.scope=function(a){if(goog.isInModuleLoader_())throw Error("goog.scope is not supported within a module.");a.call(goog.global)};goog.identity_=function(a){return a};goog.createTrustedTypesPolicy=function(a){var b=null,c=goog.global.trustedTypes;if(!c||!c.createPolicy)return b;try{b=c.createPolicy(a,{createHTML:goog.identity_,createScript:goog.identity_,createScriptURL:goog.identity_})}catch(d){goog.logToConsole_(d.message)}return b};goog.CodeLocation={DO_NOT_USE:"",DO_NOT_USE_ME_EITHER:"."};
goog.callerLocation=function(){return""};goog.callerLocationIdInternalDoNotCallOrElse=function(a){return a};var module$exports$google3$chrome$aix$tryonyou$image_analysis={ZOOM_ATTRIBUTES:["data-zoom-image","data-large_image","data-src","data-highres","data-zoom"]},module$contents$google3$chrome$aix$tryonyou$image_analysis_CONFIG={MIN_IMAGE_SIZE:170,MIN_META_IMAGE_SIZE:50,CANDIDATE_AREA_TOLERANCE:.95,MACRO_CONTAINER_CLIMB_LIMIT:8,SPATIAL_OVERLAP_THRESHOLD:.8,MIN_BASENAME_MATCH_LENGTH:4,ZOOM_ATTRIBUTES:module$exports$google3$chrome$aix$tryonyou$image_analysis.ZOOM_ATTRIBUTES};
function module$contents$google3$chrome$aix$tryonyou$image_analysis_getPrimaryImageUrl(a){if(a instanceof HTMLImageElement){var b=a.currentSrc||a.src||a.dataset.src;if(b&&!b.startsWith("data:"))return b;if(a=a.dataset.srcset||a.srcset)return a.split(",")[0].trim().split(" ")[0]}else if(a instanceof HTMLSourceElement&&a.srcset)return a.srcset.split(",")[0].trim().split(" ")[0];return""}module$exports$google3$chrome$aix$tryonyou$image_analysis.getPrimaryImageUrl=module$contents$google3$chrome$aix$tryonyou$image_analysis_getPrimaryImageUrl;
function module$contents$google3$chrome$aix$tryonyou$image_analysis_getBaseImageName(a){if(!a)return"";try{var b=a instanceof URL?a.href:a,c=new URL(b,document.baseURI||window.location.href),d=c.pathname.split("/").filter(Boolean);d=d.filter(function(k){return!(k.includes(",")||/^(?:w|h|q|f|dpr|c|ar|crop)_/i.test(k))});if(d.length===0)return"";var e=new Set("front back side editorial nomodel detail details alt alternate hero".split(" "));a="";for(b=0;b<d.length-1;b++){var f=d[b];if(e.has(f.toLowerCase())){a=
f.toLowerCase()+"_";break}}var g,m=(g=d.pop())!=null?g:"";m=m.split(".")[0];m=m.replace(/[_\-]?(?:\d+x\d+|\d+x(?!\d)|large|medium|small|master|1080v|@2x)/gi,"");var l=/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/,h=d.find(function(k){return l.test(k)});h&&(m=h+"/"+m);return a+m}catch(k){return""}}module$exports$google3$chrome$aix$tryonyou$image_analysis.getBaseImageName=module$contents$google3$chrome$aix$tryonyou$image_analysis_getBaseImageName;
function module$contents$google3$chrome$aix$tryonyou$image_analysis_isFuzzyNameMatch(a,b){return a&&b?a===b||b.length>=module$contents$google3$chrome$aix$tryonyou$image_analysis_CONFIG.MIN_BASENAME_MATCH_LENGTH&&a.startsWith(b+"_")||a.length>=module$contents$google3$chrome$aix$tryonyou$image_analysis_CONFIG.MIN_BASENAME_MATCH_LENGTH&&b.startsWith(a+"_"):!1}
function module$contents$google3$chrome$aix$tryonyou$image_analysis_extractImageFromMetadata(){var a=document.querySelector('meta[property="og:image"], meta[name="og:image"], meta[itemprop="image"]');if(!a||!a.content)return null;try{var b=new URL(a.content)}catch(n){return null}a=b.origin+b.pathname;b=module$contents$google3$chrome$aix$tryonyou$image_analysis_getBaseImageName(a);var c=document.querySelectorAll("img, picture source");c=(0,$jscomp.makeIterator)(Array.from(c));var d=c.next(),e;try{for(;!d.done;d=
c.next()){var f=d.value,g=module$contents$google3$chrome$aix$tryonyou$image_analysis_getPrimaryImageUrl(f);if(g){var m=module$contents$google3$chrome$aix$tryonyou$image_analysis_getBaseImageName(g),l=g.includes(a)||module$contents$google3$chrome$aix$tryonyou$image_analysis_isFuzzyNameMatch(b,m);if(l){var h=null;if(f instanceof HTMLImageElement)h=f;else{var k=f.closest("picture");k&&(h=k.querySelector("img"))}if(h&&h.offsetParent!==null&&h.clientWidth>module$contents$google3$chrome$aix$tryonyou$image_analysis_CONFIG.MIN_META_IMAGE_SIZE)return h}}}}finally{d&&
!d.done&&(e=c.return)&&e.call(c)}return null}
function module$contents$google3$chrome$aix$tryonyou$image_analysis_findLargestViewportImageGroups(){var a=document.querySelectorAll("img"),b=[],c=window.innerHeight||document.documentElement.clientHeight,d=window.innerWidth||document.documentElement.clientWidth;a=(0,$jscomp.makeIterator)(a);var e=a.next(),f;try{for(;!e.done;e=a.next()){var g=e.value,m=g.getBoundingClientRect();if(!(m.width<module$contents$google3$chrome$aix$tryonyou$image_analysis_CONFIG.MIN_IMAGE_SIZE||m.height<module$contents$google3$chrome$aix$tryonyou$image_analysis_CONFIG.MIN_IMAGE_SIZE)){var l=
m.top<c&&m.bottom>0&&m.left<d&&m.right>0;if(l){var h=window.getComputedStyle(g);if(!(h.visibility==="hidden"||Number(h.opacity)<.1)){var k=Math.min(m.right,d)-Math.max(m.left,0),n=Math.min(m.bottom,c)-Math.max(m.top,0);b.push({element:g,area:k*n,rect:m})}}}}}finally{e&&!e.done&&(f=a.return)&&f.call(a)}b.sort(function(p,u){return u.area-p.area});if(b.length===0)return[];var r=b[0].area;c=b.filter(function(p){return p.area>=r*module$contents$google3$chrome$aix$tryonyou$image_analysis_CONFIG.CANDIDATE_AREA_TOLERANCE});
b=[];c=(0,$jscomp.makeIterator)(c);d=c.next();var t;try{for(f={};!d.done;f={c$jscomp$2:void 0},d=c.next()){f.c$jscomp$2=d.value;var q=b.find(function(p){return function(u){var v=u[0];u=Math.max(0,Math.min(p.c$jscomp$2.rect.right,v.rect.right)-Math.max(p.c$jscomp$2.rect.left,v.rect.left));v=Math.max(0,Math.min(p.c$jscomp$2.rect.bottom,v.rect.bottom)-Math.max(p.c$jscomp$2.rect.top,v.rect.top));u*=v;v=p.c$jscomp$2.area;return u/v>module$contents$google3$chrome$aix$tryonyou$image_analysis_CONFIG.SPATIAL_OVERLAP_THRESHOLD}}(f));
q?q.push(f.c$jscomp$2):b.push([f.c$jscomp$2])}}finally{d&&!d.done&&(t=c.return)&&t.call(c)}t=(0,$jscomp.makeIterator)(b);q=t.next();var w;try{for(c={};!q.done;c={originalStyles:void 0,group$jscomp$2:void 0,topElement:void 0},q=t.next())if(c.group$jscomp$2=q.value,!(c.group$jscomp$2.length<=1)){f=d=-Infinity;m=g=Infinity;var y=(0,$jscomp.makeIterator)(c.group$jscomp$2),x=y.next(),A;try{for(;!x.done;x=y.next()){var z=x.value;d=Math.max(d,z.rect.left);f=Math.max(f,z.rect.top);g=Math.min(g,z.rect.right);
m=Math.min(m,z.rect.bottom)}}finally{x&&!x.done&&(A=y.return)&&A.call(y)}var C=(l=d<g&&f<m)?d+(g-d)/2:c.group$jscomp$2[0].rect.left+c.group$jscomp$2[0].rect.width/2,D=l?f+(m-f)/2:c.group$jscomp$2[0].rect.top+c.group$jscomp$2[0].rect.height/2;c.originalStyles=c.group$jscomp$2.map(function(p){return p.element.style.pointerEvents});d=[];try{c.group$jscomp$2.forEach(function(p){p.element.style.pointerEvents="auto"}),d=document.elementsFromPoint(C,D)}finally{c.group$jscomp$2.forEach(function(p){return function(u,
v){u.element.style.pointerEvents=p.originalStyles[v]}}(c))}c.topElement=d.find(function(p){return function(u){return p.group$jscomp$2.some(function(v){return v.element===u})}}(c));if(c.topElement){var B=c.group$jscomp$2.findIndex(function(p){return function(u){return u.element===p.topElement}}(c));B>0&&c.group$jscomp$2.unshift(c.group$jscomp$2.splice(B,1)[0])}}}finally{q&&!q.done&&(w=t.return)&&w.call(t)}return b}
function module$contents$google3$chrome$aix$tryonyou$image_analysis_getRelatedZoomImages(a){var b=new Set,c=module$contents$google3$chrome$aix$tryonyou$image_analysis_getBaseImageName(module$contents$google3$chrome$aix$tryonyou$image_analysis_getPrimaryImageUrl(a));if(!c||c.length<3)return[];for(var d=a.parentElement,e=0;d&&d.parentElement&&!(d instanceof HTMLBodyElement)&&e<module$contents$google3$chrome$aix$tryonyou$image_analysis_CONFIG.MACRO_CONTAINER_CLIMB_LIMIT;)d=d.parentElement,e++;if(!d)return[];
e=function(f){var g=Array.from(f.querySelectorAll("img"));f instanceof HTMLImageElement&&g.push(f);f=(0,$jscomp.makeIterator)(g);g=f.next();var m;try{for(;!g.done;g=f.next()){var l=g.value;if(l!==a){var h=module$contents$google3$chrome$aix$tryonyou$image_analysis_getPrimaryImageUrl(l);if(module$contents$google3$chrome$aix$tryonyou$image_analysis_isFuzzyNameMatch(module$contents$google3$chrome$aix$tryonyou$image_analysis_getBaseImageName(h),c))b.add(l);else{var k=(0,$jscomp.makeIterator)(module$contents$google3$chrome$aix$tryonyou$image_analysis_CONFIG.ZOOM_ATTRIBUTES),
n=k.next(),r;try{for(;!n.done;n=k.next()){var t=n.value;if(l.hasAttribute(t)){var q=l.getAttribute(t);if(q&&q.includes(c)){b.add(l);break}}}}finally{n&&!n.done&&(r=k.return)&&r.call(k)}}}}}finally{g&&!g.done&&(m=f.return)&&m.call(f)}};e(d);b.size!==0||d instanceof HTMLBodyElement||e(document.body);return Array.from(b)}function module$contents$google3$chrome$aix$tryonyou$image_analysis_ProductImageResult(){}module$exports$google3$chrome$aix$tryonyou$image_analysis.ProductImageResult=module$contents$google3$chrome$aix$tryonyou$image_analysis_ProductImageResult;
function module$contents$google3$chrome$aix$tryonyou$image_analysis_findProductImages(){var a=module$contents$google3$chrome$aix$tryonyou$image_analysis_findLargestViewportImageGroups(),b=module$contents$google3$chrome$aix$tryonyou$image_analysis_extractImageFromMetadata(),c=[];if(a.length===0||a.length>4)return{productImage:null,zoomImages:[]};a.length>1?(c=b?a.find(function(q){return q.some(function(w){return w.element===b})}):void 0,c||(a.sort(function(q,w){return q[0].rect.left-w[0].rect.left}),
c=a[0])):c=a[0];a=c[0].element;if(b){var d=c.find(function(q){return q.element===b});d&&(a=d.element)}d=module$contents$google3$chrome$aix$tryonyou$image_analysis_getBaseImageName(module$contents$google3$chrome$aix$tryonyou$image_analysis_getPrimaryImageUrl(a));var e=new Set;c=(0,$jscomp.makeIterator)(c);var f=c.next(),g;try{for(;!f.done;f=c.next()){var m=f.value,l=module$contents$google3$chrome$aix$tryonyou$image_analysis_getBaseImageName(module$contents$google3$chrome$aix$tryonyou$image_analysis_getPrimaryImageUrl(m.element));
if(module$contents$google3$chrome$aix$tryonyou$image_analysis_isFuzzyNameMatch(l,d)){m.element!==a&&e.add(m.element);var h=module$contents$google3$chrome$aix$tryonyou$image_analysis_getRelatedZoomImages(m.element),k=(0,$jscomp.makeIterator)(h),n=k.next(),r;try{for(;!n.done;n=k.next()){var t=n.value;t!==a&&e.add(t)}}finally{n&&!n.done&&(r=k.return)&&r.call(k)}}}}finally{f&&!f.done&&(g=c.return)&&g.call(c)}return{productImage:a,zoomImages:Array.from(e)}}
module$exports$google3$chrome$aix$tryonyou$image_analysis.findProductImages=module$contents$google3$chrome$aix$tryonyou$image_analysis_findProductImages;module$exports$google3$chrome$aix$tryonyou$image_analysis.IndigoAgentImpl=function(){this.currentLockedBaseName="";this.attributeObserver=this.domObserver=null;this.processedImages=new WeakSet};
module$exports$google3$chrome$aix$tryonyou$image_analysis.IndigoAgentImpl.prototype.invoke=function(){var a=module$contents$google3$chrome$aix$tryonyou$image_analysis_findProductImages();if(a.productImage){if(!this.isImageReplaced(a.productImage)){this.teardownDynamicObserver();this.currentLockedBaseName=module$contents$google3$chrome$aix$tryonyou$image_analysis_getBaseImageName(module$contents$google3$chrome$aix$tryonyou$image_analysis_getPrimaryImageUrl(a.productImage));this.applyReplacement(a.productImage,
"primary");a=(0,$jscomp.makeIterator)(a.zoomImages);var b=a.next(),c;try{for(;!b.done;b=a.next()){var d=b.value;this.applyReplacement(d,"mirror")}}finally{b&&!b.done&&(c=a.return)&&c.call(a)}this.setupDynamicObserver()}}else{var e,f;(b=window.indigo)==null||(f=(e=b).notifyNoPrimaryImageFound)==null||f.call(e)}};module$exports$google3$chrome$aix$tryonyou$image_analysis.IndigoAgentImpl.prototype.reset=function(){this.teardownDynamicObserver();this.processedImages=new WeakSet};
module$exports$google3$chrome$aix$tryonyou$image_analysis.IndigoAgentImpl.prototype.isImageReplaced=function(a){var b;return((b=window.indigo)==null?void 0:b.isReplacedByUserAgent)!==void 0?window.indigo.isReplacedByUserAgent(a):this.processedImages.has(a)};module$exports$google3$chrome$aix$tryonyou$image_analysis.IndigoAgentImpl.prototype.applyReplacement=function(a,b){if(!this.isImageReplaced(a)){this.processedImages.add(a);var c;(c=window.indigo)==null||c.startImageReplacement(a,{disposition:b})}};
module$exports$google3$chrome$aix$tryonyou$image_analysis.IndigoAgentImpl.prototype.processDynamicElement=function(a){var b=null;if(a instanceof HTMLImageElement)b=a;else if(a instanceof HTMLSourceElement){var c=a.closest("picture");c&&(b=c.querySelector("img"))}if(!b)return!1;if(this.isImageReplaced(b))return!0;a=module$contents$google3$chrome$aix$tryonyou$image_analysis_getPrimaryImageUrl(a);if(!a)return!1;a=module$contents$google3$chrome$aix$tryonyou$image_analysis_getBaseImageName(a);return a?
module$contents$google3$chrome$aix$tryonyou$image_analysis_isFuzzyNameMatch(a,this.currentLockedBaseName)?(this.applyReplacement(b,"mirror"),!0):!1:!1};module$exports$google3$chrome$aix$tryonyou$image_analysis.IndigoAgentImpl.prototype.processElementAndObserve=function(a,b){this.processDynamicElement(a)||this.attributeObserver.observe(a,b)};
module$exports$google3$chrome$aix$tryonyou$image_analysis.IndigoAgentImpl.prototype.setupDynamicObserver=function(){var a=this;if(this.currentLockedBaseName&&!this.domObserver){this.attributeObserver=new MutationObserver(function(f){for(var g=0;g<f.length;g++){var m=f[g].target;a.processDynamicElement(m)}});for(var b={attributes:!0,attributeFilter:["src","srcset","data-src","data-srcset"]},c=document.querySelectorAll("img, picture > source"),d=0;d<c.length;d++){var e=c[d];e instanceof HTMLImageElement&&
this.isImageReplaced(e)||this.attributeObserver.observe(e,b)}this.domObserver=new MutationObserver(function(f){for(var g=0;g<f.length;g++)for(var m=f[g].addedNodes,l=0;l<m.length;l++){var h=m[l];if(h.nodeType===1)if(h instanceof HTMLImageElement||h instanceof HTMLSourceElement)a.processElementAndObserve(h,b);else{h=h.querySelectorAll("img, picture > source");for(var k=0;k<h.length;k++)a.processElementAndObserve(h[k],b)}}});this.domObserver.observe(document.body,{childList:!0,subtree:!0})}};
module$exports$google3$chrome$aix$tryonyou$image_analysis.IndigoAgentImpl.prototype.teardownDynamicObserver=function(){this.domObserver&&(this.domObserver.disconnect(),this.domObserver=null);this.attributeObserver&&(this.attributeObserver.disconnect(),this.attributeObserver=null);this.currentLockedBaseName=""};window.indigo&&window.indigo.setup(new module$exports$google3$chrome$aix$tryonyou$image_analysis.IndigoAgentImpl);
